"""Add Comment model

Revision ID: 3fb6422e2d74
Revises: f8eae5b9cb31
Create Date: 2025-08-19 16:25:56.020738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fb6422e2d74'
down_revision = 'f8eae5b9cb31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), nullable=False),
    sa.Column('password', sa.VARCHAR(length=150), nullable=False),
    sa.Column('region', sa.VARCHAR(length=100), nullable=True),
    sa.Column('crops', sa.VARCHAR(length=200), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('streak', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
